appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: IgohHVMqFSWSUreSduXVoFv08+8bWIslVbOgCmz5ESpqzdD669eqNbV760NCwWyIpMOAecmGTjNT0PF76w1Q5zEE4Thu2+b7aAmoDvpe13XFTCiODRfx5mFeXxtfvsMybkYeOv6L2Vt9puhim00T6SaKIKhGwEzjuwxcVbkbwePVe82W2PKECdezPP3w3/oEAlXQcK2+DSCa7G1NL52qhPLqKnP875raAcAFlz6p3pQvd9gMk5ccakTE4SF2hYea4zwOUuUUZwC6WVTXGP5ckcLfm/DeAOLdmR5AObmoDle2FEngUOoo5q3HTwgDML2t4FfyZFjjb9DPuFbh7N6Vj2jH2a0LEWlQ1/WCLKBKjFNkGsYofFs5K1fEr6NVkWFVHAnUSVQWwkVyl9g6rV5Xjs6h04hDPgtBYhekj/hYW87TZQ9NUJDkCKCGTYDfnZTjur+H8PLbx+teZXLliMqwbPJ5puFT4Wxj0IyVHZuAUq1+Ujj9/0bIDSJbLf3mNdoKACo8iyKXEBXZARjqSCYpyyaep/Ift/jPQp2/e02RlPikMr9c06qrZ0lQjQPfe7/dFQXx09uq6Jy7SIcL7sgI1g0h1rodw3ncSRhLnq00c6qp4ADbkN3WbZhciRk8Hyyn/egPSeiOvFuqcq6T7S7ibunmBse5ujLIlcWYMd/vT8I=}
