travis:
  secure:
    BINSTAR_TOKEN: JfTrGPkvwHttt1YtEM7cMDGjU8HBDb6H/bGGuANTxhztHMnjhhH91VStG3YP31VLaI5jsFlIA/2Ka9KwVFJ6XracrNrkLVaWp7RZLd0S1Bdqm9R59AhGP7A50QZdpCgWdLdVDVwCirVud6S+Rq995jY2f673oIBIYM5gfekHfqjEoiAGYwsjF7iln1aZVafrX4OVpwzRuyLgy4fRYqkc9GdHTICgKL05gT/vQswq1TQSH6OuzMtKGhhT9HBtlHkCLnqBhkwDw/ZRP8PTf6gveHqUEnyXnbq2uUhJO0arniTRUGpDvN1pmXahd3YGweF4Y2QB9ocOM7dyumiaCqSo+eWe5EKRu+0BGgajCbEFbdpHaLpZEq8vHeiM3zSw8tZYaaRXL70pxoC6HMI4KUuEeq858DjiOxdtoZPl6ScpSEiS2Ej4Od2a1AjRQKh2OwZPHe9/tF7iF6Pz83wW/eqN091HD/UEr+Pvakm/7kak94CehcwgX7IRP4G9lhH9Nn0i9EDrMuZeDlVZRKLmaYwkQbYCkZsZ5IuOpLx9f1jikOQHe9tFt0rCFukt/aSxSb4E2SsJuZf4l6e8VScOh16m/Zzfib23ZaUfbr+t8s91s8N0U1ixOtnIAQ/xMzWe5y+yCiyMaMEQrZiiIz/qoxDFRdN2vzgzC8sPA9091hFp3Ng=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
